# Site settings
baseURL = "https://yusbk.github.io/persbraten"
languageCode = "en-US"
title = "Persbråten Klassefesten"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2021 3NF"

# Use docs folder instead of public
publishDir = "docs"

[params]

  # Metadata for search engines and social sharing
  author = "Yusman"
  description = "3NF Persbråten Klassefest"
  shareImage = "img/3nf_logo.jpg"
  twitterHandle = "3NF"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "img/persbraten2022.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Noe å dele..."

      [[params.links.list1.link]]
        text = "Bilder"
        url = "https://yusbk.github.io/persbraten/bilder.html"

      [[params.links.list1.link]]
        text = "Video"
        url = "https://yusbk.github.io/persbraten/video.html"

  #     [[params.links.list1.link]]
  #       text = "Newsletter"
  #       url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Laste ned"

      [[params.links.list2.link]]
        text = "Kortet"
        url = "https://github.com/yusbk/persbraten/raw/master/static/img/klassefest2022.pdf"

  #     [[params.links.list2.link]]
  #       text = "Instagram"
  #       url = "#"

  #     [[params.links.list2.link]]
  #       text = "Dribbble"
  #       url = "#"

  # # Links List #3
  # [[params.links]]
  #   [params.links.list3]
  #     heading = "Network"

  #     [[params.links.list3.link]]
  #       text = "Link One"
  #       url = "#"

  #     [[params.links.list3.link]]
  #       text = "Link Two"
  #       url = "#"

  #     [[params.links.list3.link]]
  #       text = "Link Three"
  #       url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
